### ISSUE TITLE
cURL error 60: SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by TinyGang** [owncloud/richdocuments#35]
Click the "Collabora Online",
I got "cURL error 60: SSL certificate problem: self signed certificate in certificate chain" message.
Is there any way to solve this problem?

**Comment by timar** [comment]
You can add your self signed ca certificate to owncloud/resources/config/ca-bundle.crt

**Comment by TinyGang** [comment]
Thank you for your solution, it works!
But now I encounter another problem.
When I try to open the .odt file, the message says "**Not found**" .
![error](https://cloud.githubusercontent.com/assets/18278822/14337198/3fa17586-fc9e-11e5-9a8c-bdad34007a82.png)
I found the "urlsrc" is "undefined".
How can I fix it? Do you have any advice?
Thanks a lot!

**Comment by shwarz13** [comment]
owncloud9.0
Same problem.

**Comment by ucyrus** [comment]
Same to me with owncloud 9.0.1.3 running on Debian 8 with php 5.6.19, Apache 2.4.10.
"...undefinedWOPISrc...was not found on this server"
any hint welcome :-)

**Comment by timar** [comment]
The undefinedWOPISrc problem is solved by https://github.com/owncloud/richdocuments/pull/58

**Comment by ordertochaos** [comment]
timar - what self signed certificate do you add?

**Comment by hubearth** [comment]
@ordertochaos 
I'm kindda new to this. What self signed certificate should I add?
I've obtained my certificate with Let's Encrypte and there's 4 files in /etc/letsencrypt/live/collabora.exemple.org/ 
I've tried all of them and all possible combinasion.

**Comment by orboan** [comment]
Yes, I use letsencrypt with test option enabled, and trying the generated certs in /etc/nginx/certs adding any of them to owncloud/resources/config/ca-bundle.crt  does not solve the "Access denied" message. Even I get a new error in oc web ui saying the server has no Internet connection.

Please, any help or hint would be very much appreciated.
Thanks

**Comment by hubearth** [comment]
I solved my issu, but it's been a while and I can't remember how I did it. Although, one thing that solved much of my problem was to switch the docker file system from aufs to devicemapper. @orboan, are you using docker?
